[package]
name = "rdsp_cbinding"
version = "0.1.0"
authors = ["Chikashi Miyama <chikashimiyama@gmail.com>"]
edition = "2018"

[lib]
crate-type =["staticlib"]

[dependencies]
cbindgen = "0.20.0"
rdsp = { path = "../rdsp" }


